### ISSUE TITLE
Dependency with qmain is always added, and strange directories

### ISSUE THREAD

**Issue by mkentie** [qtproject/qt-labs-vstools#48]
I'm using the Qt VS Tools 3.4.1. Previously I was using 2.10. One of the applications in our solution is an MFC application that contains a single UI file that requires the moc compiler. So this application's vcxproj is marked as a Qt project. Previously this worked fine. After updating to 3.4.1, however, when compiling I get the error

qtmaind.lib(qtmain_win.obj) : error LNK2019: unresolved external symbol main referenced in function WinMain

As seen in the screenshot, vcxproj file generated by the VS Addin always links with qtmain(d).lib. Furthermore, strange hard-coded directories are added to the library paths (mysql, etc). I assume this generated vcxproj file is the issue, somehow?

After some searching, I tried adding the -= entrypoint flag to the qmake settings, but this doesn't help

**To Reproduce**
Convert an MFC project (which uses MFC's WinMain) to a Qt project by adding the 'QtVS_v304' keyword, props and target files.

**Expected behavior**
Qt projects shouldn't always link with qtmain.lib, or it should be able to be turned off.

**Screenshots**

<img width="1252" height="49" alt="Image" src="https://github.com/user-attachments/assets/b18a99ab-93ab-4230-860c-96536b1dadeb" />

<img width="660" height="58" alt="Image" src="https://github.com/user-attachments/assets/7e628230-97b1-4ad2-8ed3-01efc15ed8ed" />

**Desktop (please complete the following information):**
 - Qt VS Tool Version Qt VS Tools 3.4.1
 - Visual Studio version VS2022
