### ISSUE TITLE
VS Qt Designer Custom Widget compile fail after upgrade to 3.3.1

### ISSUE THREAD

**Issue by KHeresy** [qtproject/qt-labs-vstools#42]
**Describe the bug**
The Visual C++ Qt Designer plugin project fail to compile after Qt VS Tools upgrade to 3.3.1.
The project work fine in 3.3.0.

Error happen with official example project generate by new project wizard.

**To Reproduce**
1. Open Visual Studio, choose "Create a new project"
2. choose "Qt Designer Custom Widget", and follow the wizard to create a new project
3. build solution
4. error happened: `MSB4181`, `The "QtRunWork" task returned false but did not log an error.`
   - may build sucessful first time, but fail when rebuild

**Expected behavior**
Build successful

**Screenshots**

**Desktop (please complete the following information):**
 - Qt VS Tool Version 3.3.1
 - Qt SDK 6.8.1
 - Visual Studio 2022 17.12.3

**Additional context**
build fail log
```
1>------ Build started: Project: QtDesignerWidget1, Configuration: Debug x64 ------
1> Qt/MSBuild: 3.3.1.0
1>Reading Qt configuration (E:/QtSDK/6/bin/qmake)
1> Qt: 6.8.1
1>moc QtDesignerWidget1Plugin.h
1> E:\QtDesignerPlugin\QtDesignerWidget1\QtDesignerWidget1Plugin.h(9:1): error: Undefined interface
1>C:\Users\Heresy\AppData\Local\QtMsBuild\qt_work.targets(138,5): error MSB4181: The "QtRunWork" task returned false but did not log an error.
1>Done building project "QtDesignerWidget1.vcxproj" -- FAILED.
```

**Comment by kaheimri** [comment]
Thank you very much for reporting this issue; it has been recorded in our public bug tracker, where all further updates will be shared: [QTVSADDINBUG-1272](https://bugreports.qt.io/browse/QTVSADDINBUG-1272)

As a temporary solution, you can roll back to the previous working version by following these steps:

- Uninstall the current version (3.3.1.1) in Visual Studio.
- Download version 3.3.0 from this link: https://download.qt.io/official_releases/vsaddin/3.3.0/.
- Install version 3.3.0.
- Disable the auto-update functionality in the Visual Studio Extension Manager to prevent future automatic updates.

If you have any additional questions or need further assistance, please feel free to reach out.

**Comment by KHeresy** [comment]
The issue had been resolved in 3.4.0.1
